name: notebooks
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: any
  cupertino_icons: any
  dartz: any
  equatable: any
  flash: any
  flutter:
    sdk: flutter
  flutter_bloc: any
  flutter_native_splash: any
  flutter_screenutil: any
  get_it: any
  go_router: any
  intl: any
  introduction_screen: any
  lottie: any
  path_provider: any
  settings_ui: any
  shared_preferences: any
  sqflite: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app/deeNotes_logo_300px.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app/deeNotes_logo_1024px.png"
  adaptive_icon_foreground: "assets/images/app/logo_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/notebooks/
    - assets/images/app/
    - assets/animations/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
